name: Conan CMake Project CI

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release
  BUILD_PATH: ${{github.workspace}}/build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.22.1'

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 2.1.0

    - name: Configure Conan
      run: conan profile detect --force
    
    - name: Install dependencies with Conan
      run: conan install . --build=missing

    - name: Configure CMake
      run: cmake -B ${{env.BUILD_PATH}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=Release/generators/conan_toolchain.cmake

    - name: Build
      run: cmake --build ${{env.BUILD_PATH}}

    - name: Test
      working-directory: ${{env.BUILD_PATH}}
      run: ctest -C ${{env.BUILD_TYPE}}
